@startuml

state START
state INIT
state CONFIGURE
state TX
state WAIT_TX
state OBSERVE_TX
state WAIT_REPLY
state GOT_REPLY
state RESET
state DONE

START --> INIT : true
INIT --> CONFIGURE : true
CONFIGURE --> TX : true
TX --> WAIT_TX : true
WAIT_TX --> OBSERVE_TX : true
OBSERVE_TX --> WAIT_REPLY : NET.tx_done=true
WAIT_REPLY --> GOT_REPLY : NET.rx_done=true
GOT_REPLY --> RESET : true
RESET --> TX : true
DONE --> INIT : true

note right of START
{
}
end note

note right of INIT
{
  "_send_regs": {
    "libnet_create": true,
    "libnet_destroy": false,

    "eth_enabled": true,
    "ip4_enabled": true,
    "icmp4_enabled": true,

    "tx_fire": false,
    "rx_fire": false
  }
}
end note

note right of CONFIGURE
{
  "_send_regs": {
    "libnet_create": true,
    "libnet_device": "eno1",

    "eth_enabled": true,
    "eth_src_mac": "ec:b1:d7:52:8c:52",
    "eth_dst_mac": "5c:d9:98:5f:16:54",
    "eth_type": 2048,

    "ip4_enabled": true,
    "ip4_src": "192.168.0.105",
    "ip4_dst": "192.168.0.1",
    "ip4_ttl": 64,

    "icmp4_enabled": true,
    "icmp4_type": 8,
    "icmp4_code": 0,
    "icmp4_id": 4242,
    "icmp4_seq": 0,
    "icmp4_payload": "MPP-HELLO-0001",

    "pcap_create": true,
    "pcap_device": "eno1",
    "pcap_filter": "icmp and ether dst ec:b1:d7:52:8c:52",
    "pcap_set_filter": true
  }
}
end note

note right of TX
{
  "_send_regs": {
    "tx_fire": true,
    "rx_fire": false
  }
}
end note

note right of WAIT_TX
{
  "_send_regs": {
    "net_rx_enable": false,
    "tx_fire": false,
    "rx_fire": false
  }
}
end note

note right of OBSERVE_TX
{
  "_send_regs": {
    "net_rx_enable": false,
    "tx_fire": false,
    "rx_fire": false
  }
}
end note

note right of WAIT_REPLY
{
  "_send_regs": {
    "net_rx_enable": true,
    "tx_fire": false,
    "rx_fire": true
  }
}
end note

note right of GOT_REPLY
{
  "_send_regs": {
    "tx_fire": false,
    "rx_fire": false
  }
}
end note

note right of RESET
{
  "_send_regs": {
    "tx_fire": false,
    "rx_fire": false,
    "NET.tx_done": false,
    "NET.rx_done": false
  }
}
end note

note right of DONE
{
  "_send_regs": {
    "libnet_destroy": true,
    "pcap_destroy": true,
    "net_rx_enable": false,
    "tx_fire": false,
    "rx_fire": false
  }
}
end note

@enduml
